spring:
  application:
    name: human-resources-project

  datasource:
    url: jdbc:postgresql://localhost:5432/human_resources
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: "k2joYbebeplmCvRz1baVSb80fc8FIJM4asfadasfdhafdhadfh"

